vscode:
  extensions:
    - golang.go@0.16.2:KwEZ/3KscWWNBDyu17+5lw==
    - esbenp.prettier-vscode@5.6.0:o6BL3Pchy5KVBxQAzrFZ2A==
    - zxh404.vscode-proto3@0.4.2:ZnPmyF/Pb8AIWeCqc83gPw==
    - bbenoist.QML@1.0.0:QtmLlm4mroEpaP9RgoL++g==
image:
  file: .gitpod.Dockerfile
tasks:
  - command: git lfs install && git config lfs.https://gitlab.com/timeterm/timeterm.git/info/lfs.locksverify true

