version: '3'

services:
  postgres:
    image: postgres:12.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timeterm
    restart: on-failure

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8432:8080"

  nats-streaming:
    image: nats-streaming:0.18.0-alpine
    restart: always
    command: nats-streaming-server -store file -dir datastore
    ports:
      - "4222:4222"
