version: '3'

services:
  postgres:
    image: postgres:12.3-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timeterm
    restart: on-failure

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
