baseURL = "http://docs.timeterm.nl/"
languageCode = "nl-NL"
title = "Timeterm documentatie"
theme = "book"

DefaultContentLanguage = "nl"
copyright = "Timeterm"

[params]
  BookTheme = "auto"
  BookMenuBundle = "/menu"

